from bitrix24 import *

bx24 = Bitrix24('https://eurotechpromg.bitrix24.ru/rest/308/2gnr740m6pfywjof/')
print(bx24.callMethod('tasks.task.getFields'))

print(bx24.callMethod('tasks.task.getFields'))
{'fields':
# {'ID': {'title': 'ID', 'type': 'integer', 'primary': True},
# 'PARENT_ID': {'title': 'ID базовой задачи', 'type': 'integer', 'default': 0},

 'TITLE': {'title': 'Название', 'type': 'string', 'required': True},
 'DESCRIPTION': {'title': 'Описание', 'type': 'string'},
 'MARK': {'title': 'Оценка', 'type': 'enum', 'values': {'N': 'Отрицательная', 'P': 'Положительная'},'default': None},
 'PRIORITY': {'title': 'Приоритет', 'type': 'enum', 'values': {'2': 'Высокий', '1': 'Средний', '0': 'Низкий'}, 'default': 1},
 'STATUS': {'title': 'Статус', 'type': 'enum', 'values': {'2': 'Ждет выполнения', '3': 'Выполняется', '4': 'Ожидает контроля', '5': 'Завершена', '6': 'Отложена'}, 'default': 2},
 'UF_TASK_WEBDAV_FILES': {'title': 'Загрузить файлы', 'type': 'disk_file'},
# 'UF_CRM_TASK': {'title': 'Элементы CRM', 'type': 'crm'},

#
 'DATE_START': {'title': 'Дата начала', 'type': 'datetime', 'default': None},
 'DEADLINE': {'title': 'Крайний срок', 'type': 'datetime', 'default': None},
 'RESPONSIBLE_ID': {'title': 'Исполнитель', 'type': 'integer', 'required': True},
 #
 # 'MULTITASK': {'title': 'Множественная задача', 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'NOT_VIEWED': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'REPLICATE': {'title': 'Повторяемая задача', 'type': 'enum', 'vjalues': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'GROUP_ID': {'title': 'Проект', 'type': 'integer', 'default': 0},
 # 'STAGE_ID': {'title': 'Стадия', 'type': 'integer', 'default': 0},
 # 'CREATED_BY': {'title': 'Постановщик', 'type': 'integer', 'required': True},
 # 'CREATED_DATE': {'title': None, 'type': 'datetime'},
 # 'ACCOMPLICES': {'title': None, 'type': 'array'}, 'AUDITORS': {'title': None, 'type': 'array'},
 # 'CHANGED_BY': {'title': 'Изменил', 'type': 'integer'},
 # 'CHANGED_DATE': {'title': 'Дата изменения', 'type': 'datetime'},
 # 'STATUS_CHANGED_BY': {'title': 'Изменил статус', 'type': 'integer'},
 # 'STATUS_CHANGED_DATE': {'title': 'Дата изменения статуса', 'type': 'datetime'},
 # 'CLOSED_BY': {'title': 'Закрыл задачу', 'type': 'integer', 'default': None},
 # 'CLOSED_DATE': {'title': 'Дата закрытия', 'type': 'datetime', 'default': None},
 # 'ACTIVITY_DATE': {'title': None, 'type': 'datetime', 'default': None},
 # 'START_DATE_PLAN': {'title': 'Плановое начало', 'type': 'datetime', 'default': None},
 # 'END_DATE_PLAN': {'title': 'Плановое завершение', 'type': 'datetime', 'default': None},
 # 'GUID': {'title': 'GUID', 'type': 'string', 'default': None},
 # 'XML_ID': {'title': 'XML_ID', 'type': 'string', 'default': None},
 # 'COMMENTS_COUNT': {'title': 'Кол-во комментариев', 'type': 'integer', 'default': 0},
 # 'SERVICE_COMMENTS_COUNT': {'title': None, 'type': 'integer', 'default': 0},
 # 'NEW_COMMENTS_COUNT': {'title': None, 'type': 'integer', 'default': 0},
 # 'ALLOW_CHANGE_DEADLINE': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'ALLOW_TIME_TRACKING': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'TASK_CONTROL': {'title': 'Принять работу', 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'ADD_IN_REPORT': {'title': 'Добавить в отчет', 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'FORKED_BY_TEMPLATE_ID': {'title': 'Создано из шаблона', 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'TIME_ESTIMATE': {'title': 'Затраченое время', 'type': 'integer'},
 # 'TIME_SPENT_IN_LOGS': {'title': 'Затраченое время из истории изменений', 'type': 'integer'},
 # 'MATCH_WORK_TIME': {'title': 'Пропустить выходные дни', 'type': 'integer'},
 # 'FORUM_TOPIC_ID': {'title': 'FORUM_TOPIC_ID', 'type': 'integer'},
 # 'FORUM_ID': {'title': 'FORUM_ID', 'type': 'integer'},
 # 'SITE_ID': {'title': 'SITE_ID', 'type': 'string'},
 # 'SUBORDINATE': {'title': 'Задача подчиненного', 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': None},
 # 'FAVORITE': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': None},
 # 'EXCHANGE_MODIFIED': {'title': 'EXCHANGE_MODIFIED', 'type': 'datetime', 'default': None},
 # 'EXCHANGE_ID': {'title': 'EXCHANGE_ID', 'type': 'integer', 'default': None},
 # 'OUTLOOK_VERSION': {'title': 'OUTLOOK_VERSION', 'type': 'integer', 'default': None},
 # 'VIEWED_DATE': {'title': 'Дата последнего просмотра', 'type': 'datetime'},
 # 'SORTING': {'title': 'Индекс сортировки', 'type': 'double'},
 # 'DURATION_PLAN': {'title': 'Затрачено (план)', 'type': 'integer'},
 # 'DURATION_FACT': {'title': 'Затрачено (фактически)', 'type': 'integer'},
 # 'CHECKLIST': {'title': None, 'type': 'array'},
 # 'DURATION_TYPE': {'title': 'DURATION_TYPE', 'type': 'enum', 'values': ['secs', 'mins', 'hours', 'days', 'weeks', 'monts', 'years'], 'default': 'days'},
 # 'IS_MUTED': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'IS_PINNED': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'IS_PINNED_IN_GROUP': {'title': None, 'type': 'enum', 'values': {'Y': 'Да', 'N': 'Нет'}, 'default': 'N'},
 # 'UF_CRM_TASK': {'title': 'Элементы CRM', 'type': 'crm'},
 # 'UF_TASK_WEBDAV_FILES': {'title': 'Загрузить файлы', 'type': 'disk_file'},
 # 'UF_MAIL_MESSAGE': {'title': None, 'type': 'mail_message'},
 # 'UF_AUTO_511608294789': {'title': 'Коэффициент сложности', 'type': 'double'}}}
